### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by alex3236** [Hi-awaBlack/Requirements-MCDR#1]
1. "Installation of dependency {moduleName} successful."
  Commonly we use: Successfully installed {moduleName}
2. Naming
  In python, you should name a function(method) or variable `like_this`, `notThis`. see PEP8 for more infomation.
3. typo
  https://github.com/Hi-awaBlack/Requirements-MCDR/blob/ba1a061e56865f6448ecca39b554a13c7aba83cf/requirements/__init__.py#L25 should be dependencies.
4. "pypi source" should not be called "mirror source". meanwhile, you should make official source default, but not tencent mirror.
5. if the installation fails, raise an error or return a (boolean?) value to plugins, otherwise they have no way of knowing if they can continue. take the code you provided in the README as an example. if install fails, there will be a exception:
```
def on_load(server: PluginServerInterface, prev_module):
     server.get_plugin_instance('requirements').installModule(server, 'requests')
     import request
     ^^^^^^^^^^^^^^ AN EXCEPTION WILL RAISES HERE
```
unless they check it:
```
# ...
try:
    import requests
except:
    # ...
```
the better way is:
```python
# ...
if server.get_plugin_instance('requirements').installModule(server, 'requests'):
    import requests
else:
    # ...
```
6. (CRITICAL) dont assume the user's environment. pip in the PATH and the running python may not match. use `[sys.executable, '-m', 'pip']` instead.
7. (CRITICAL) All these will run on main executor which means MCDR can not handle (almost) anything while installing process. that is FATAL.
8. releasing a release with a version number of 1.0.0 when you haven't fully checked the code is not advisable. Make it 0.1.0 and mark it as pre-release.

**Comment by Hi-awaBlack** [comment]
thank you for pointing out these errors, i will fix them as soon as possible!!!

**Comment by Hi-awaBlack** [comment]
Regarding Article 7:

if the main process is not blocked during installation, the plugin may import the package before the installation is completed, causing an error. 

Or are there other ways to solve this problem?

**Comment by Hi-awaBlack** [comment]
Regarding Article 8:

I will delete the first release.

**Comment by Hi-awaBlack** [comment]
i have modified the code according to your opinions (except for point 7, see [here](https://github.com/Hi-awaBlack/Requirements-MCDR/issues/1#issuecomment-1952670708) for the reason), this is the [new version](https://github.com/Hi-awaBlack/Requirements-MCDR/releases/tag/v0.1.0-beta).

**Comment by Hi-awaBlack** [comment]
This issue will be closed.
